"""Alembic environment configuration."""

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# ---------------------------------------------------------------------------
# Import the shared declarative Base
# ---------------------------------------------------------------------------
from shared.entity.base import Base  # noqa: E402

# ---------------------------------------------------------------------------
# Import every SQLAlchemy entity so that it is registered with Base.metadata.
# Alembic autogeneration inspects Base.metadata to detect schema changes.
# ---------------------------------------------------------------------------
from shared.entity.processed_event_entity import ProcessedEventRecord  # noqa: F401, E402
from block.entity.block_entity import BlockRecord  # noqa: F401, E402
from follow.entity.follow_entity import FollowRecord  # noqa: F401, E402
from post.entity.collab_entity import CollabRecord  # noqa: F401, E402
from post.entity.comment_post_entity import CommentPostRecord  # noqa: F401, E402
from post.entity.user_post_comment_interaction_entity import (  # noqa: F401, E402
    UserPostCommentInteractionRecord,
)
from post.entity.user_post_interactions_entity import (  # noqa: F401, E402
    UserPostInteractionsRecord,
)
from pipeline.entity.post.post_features_entity import PostFeaturesRecord  # noqa: F401, E402
from pipeline.entity.post.post_tag_features_entity import (  # noqa: F401, E402
    PostTagFeaturesRecord,
)
from pipeline.entity.user.user_features_entity import UserFeaturesRecord  # noqa: F401, E402
from pipeline.entity.user.user_creator_features_entity import (  # noqa: F401, E402
    UserCreatorFeaturesRecord,
)

# ---------------------------------------------------------------------------
# Alembic Config object (gives access to values in alembic.ini)
# ---------------------------------------------------------------------------
config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The metadata object that autogenerate compares against the live DB schema
target_metadata = Base.metadata
ALEMBIC_MANAGED_INDEXES = {"ix_post_features_semantic_embedding_hnsw"}

# ---------------------------------------------------------------------------
# DATABASE_URL comes from the environment; never hard-code credentials here.
# ---------------------------------------------------------------------------
database_url = os.environ["DATABASE_URL"]


# ---------------------------------------------------------------------------
# Render pgvector columns in autogenerated revisions with the required import.
# ---------------------------------------------------------------------------
from pgvector.sqlalchemy import Vector  # noqa: E402


def render_item(type_, object_, autogen_context):
    if type_ == "type" and isinstance(object_, Vector):
        autogen_context.imports.add("from pgvector.sqlalchemy import Vector")
        return f"Vector({object_.dim})"

    return False


def include_object(object_, name, type_, reflected, compare_to):
    if type_ == "index" and reflected and name in ALEMBIC_MANAGED_INDEXES:
        return False

    return True


# ---------------------------------------------------------------------------
# Migration runners
# ---------------------------------------------------------------------------


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (no live DB connection needed).

    This generates the SQL script without connecting to the database.
    """
    context.configure(
        url=database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        render_item=render_item,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (executes against a live DB)."""
    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = database_url

    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            render_item=render_item,
            include_object=include_object,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
