from enum import Enum


POST_VIEW_WEIGHT = 1.0
FAST_SKIP_WEIGHT = -1.0

POST_LIKE_WEIGHT = 2.0
POST_UNLIKE_PENALISATION_WEIGHT = 0.8

POST_COMMENT_LIKE_WEIGHT = 1.0
POST_COMMENT_UNLIKE_PENALISATION_WEIGHT = 0.3

POST_COMMENT_WEIGHT = 2.5
POST_COMMENT_DELETED_PENALISATION_WEIGHT = 0.625
COMMENT_ACCUMULATION_DECAY = 0.5

POST_SHARE_WEIGHT = 3.5
POST_UNSHARE_PENALISATION_WEIGHT = 1.05

COLLAB_REQUEST_WEIGHT = 2.0
COLLAB_REQUEST_ACCEPT_WEIGHT = 3.0
COLLAB_REQUEST_DELETED_PENALISATION_WEIGHT = 0.4


class InteractionSourceMultiplier(float, Enum):
    HOME_FEED = 1.0
    USER_PROFILE = 1.15
    SEARCH = 1.25