from enum import Enum


POST_VIEW_WEIGHT = 1.0
FAST_SKIP_WEIGHT = -1.0

POST_LIKE_WEIGHT = 2.0
POST_UNLIKE_PENALISATION_WEIGHT = 0.8

POST_COMMENT_LIKE_WEIGHT = 1.0
POST_COMMENT_UNLIKE_PENALISATION_WEIGHT = 0.3

POST_COMMENT_WEIGHT = 2.5
POST_COMMENT_DELETED_PENALISATION_WEIGHT = 0.625
COMMENT_ACCUMULATION_DECAY = 0.5

POST_SHARE_WEIGHT = 3.5
POST_UNSHARE_PENALISATION_WEIGHT = 1.05

COLLAB_REQUEST_WEIGHT = 2.0
COLLAB_REQUEST_ACCEPT_WEIGHT = 3.0
COLLAB_REQUEST_DELETED_PENALISATION_WEIGHT = 0.4

FOLLOW_WEIGHT = 2.0
UNFOLLOW_PENALISATION_WEIGHT = 2.0

class InteractionSourceMultiplier(float, Enum):
    HOME_FEED = 1.0
    USER_PROFILE = 1.15
    SEARCH = 1.25
# --- RANKING WEIGHTS ---
RANKING_WEIGHT_IMPRESSIONS = 0.0
RANKING_WEIGHT_VIEWS = 0.0
RANKING_WEIGHT_LIKES = 0.0
RANKING_WEIGHT_COMMENTS = 0.0
RANKING_WEIGHT_SHARES = 0.0
RANKING_WEIGHT_FAST_SKIPS = 0.0
RANKING_WEIGHT_COLLAB_REQUESTS = 0.0
RANKING_WEIGHT_WATCH_TIME_AVG_PERCENT = 0.0

RANKING_WEIGHT_DECAYED_IMPRESSIONS = 0.0
RANKING_WEIGHT_VIEWS_ENGAGEMENT = 0.0
RANKING_WEIGHT_DECAYED_LIKES = 0.0
RANKING_WEIGHT_DECAYED_COMMENTS = 0.0
RANKING_WEIGHT_DECAYED_SHARES = 0.0
RANKING_WEIGHT_DECAYED_FAST_SKIPS = 0.0
RANKING_WEIGHT_DECAYED_COLLAB_REQUESTS = 0.0

RANKING_WEIGHT_FOLLOWS_CREATOR = 0.0
RANKING_WEIGHT_CREATOR_AFFINITY = 0.0
RANKING_WEIGHT_TAGS_AFFINITY = 0.0
RANKING_WEIGHT_RETRIEVED_SOURCE_SCORE = 0.0
